# https://github.com/jeffreytse/jekyll-theme-yat/?tab=readme-ov-file#remote-theme-method-with-jekyll-remote-theme-plugin

remote_theme: jeffreytse/jekyll-theme-yat@v1.10.0
plugins:
- jekyll-remote-theme

title: Title
email: ohno.github@gmail.com
author: Shuhei Ohno
copyright: "© 2025-{currentYear} {author}"
description: "description description description description description description description description description description"
night_mode: "manual"
brand_color: "#EA5A47"

defaults:
  home:
    heading: "HEADING HEADING HEADING"
    subheading: "subheading subheading subheading"
